### PR TITLE
made it a bit less disrespectful, why call people nerds?

### PR DESCRIPTION
**Pull request by DoxrGitHub**
yo, using a nerd face for a user prompt might seem like whatevs, but lemme break it down. It's like saying only "nerds" care about tech or asking stuff to ai, which is kinda meh. Tech and curiosity aren't just for one group. Using a nerd face can make peeps feel like their questions aren't taken seriously, I think it is kinda rude and we should stop this nonsense genralization

think about it: we're all here to learn and swap ideas. stereotyping someone as a "nerd" just coz they got a question and are using their tools can shut down convos tbh. We gotta create a vibe where everyone feels cool jumping in without feeling judged based on lame stereotypes. We're a crew, so ditch the nerd face and embrace the mix of interests and backgrounds that make this place rad. Let's lose the labels and focus on what really matters—learning, sharing, and growing together.

hope you consider me
a maybe tech nerd, doxr

### CODE REVIEW

**Comment by DoxrGitHub** [comment]
fun little pings, I don't want to wait a month for this to be pulled (sorry if I sound rude)

@mattt 
@zeke 
@bfirsh 
@evilstreak

**Comment by Pwntus** [comment]
Hi @DoxrGitHub
Sorry for any misunderstanding. The :disguised_face: character is `disguised face (U+1F978)`, and not intended to convey anything specific.

**Comment by DoxrGitHub** [comment]
oh. sorry. it looks like a nerd face. wow, I really am kinda dumb

**Comment by zeke** [comment]
No worries. Thanks for the consideration. Closing.

**Pull request closed without merging**
